<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert-lastname-empty</name>
   <tag></tag>
   <elementGuidId>e10430cc-e54e-470b-a4b7-906a48b44b8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//ol[@class='fieldsInLine']/li[3]/span[@class='validation-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//ol[@class='fieldsInLine']/li[3]/span[@class='validation-error']</value>
   </webElementProperties>
</WebElementEntity>
