<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Button_orang</name>
   <tag></tag>
   <elementGuidId>4946bbbb-28fe-4d35-b613-a079db6427e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[.='Account']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[.='Account']</value>
   </webElementProperties>
</WebElementEntity>
