<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text</name>
   <tag></tag>
   <elementGuidId>64097841-4f49-497f-b424-8e84a2d7083a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>h3</value>
   </webElementProperties>
</WebElementEntity>
