<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu-adm</name>
   <tag></tag>
   <elementGuidId>6580ac6b-cc90-4770-aa34-5684b046b3db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[.='Admin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[.='Admin']</value>
   </webElementProperties>
</WebElementEntity>
