<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message</name>
   <tag></tag>
   <elementGuidId>58b3ad00-7f94-4390-a5bc-3a4bd3ee08f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.message</value>
   </webElementProperties>
</WebElementEntity>
